[tools]
actionlint = "1.7.4"
bun        = "1.2.18"
node       = "22.17.0"
pre-commit = "4.2.0"
shellcheck = "0.10.0"
uv         = "0.7.19"
yamllint   = "1.37.1"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
