[tools]
actionlint              = "1.7.4"
bun                     = "1.2.5"
node                    = "22.14.0"
"npm:markdownlint-cli2" = "0.17.2"
"npm:renovate"          = "39.83.5"
pre-commit              = "4.1.0"
shellcheck              = "0.10.0"
uv                      = "0.6.6"
yamllint                = "1.35.1"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
