[tools]
actionlint = "1.7.4"
bun        = "1.2.19"
node       = "22.17.1"
pre-commit = "4.2.0"
shellcheck = "0.10.0"
terraform  = "1.6.6"
tflint     = "0.58.1"
uv         = "0.8.3"
yamllint   = "1.37.1"

[settings.npm]
bun = true

[settings.pipx]
uvx = true
