[tools]
aqua                    = "2.53.9"
actionlint              = "1.7.4"
cosign                  = "2.5.3"
bun                     = "1.2.21"
flux2                   = "2.6.4"
hadolint                = "2.12.0"
kind                    = "0.30.0"
kubectl                 = "1.34.0"
markdownlint-cli2       = "0.18.1"
node                    = "22.17.1"
pre-commit              = "4.3.0"
shellcheck              = "0.11.0"
slsa-verifier           = "2.7.0"
terraform               = "1.6.6"
tflint                  = "0.59.1"
uv                      = "0.8.14"
yamllint                = "1.37.1"
"aqua:kyverno/chainsaw" = "0.2.13"
"npm:renovate"          = "41.91.3"

[settings]
disable_backends = ["asdf", "dotnet", "gem", "spm", "vfox"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true
