[tools]
bun               = "1.3.0"
markdownlint-cli2 = "0.18.1"
node              = "22.20.0"
uv                = "0.9.3"

[settings]
disable_backends = ["asdf", "dotnet", "gem", "spm", "vfox"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true
