[tools]
aqua                    = "2.53.7"
actionlint              = "1.7.4"
cosign                  = "2.5.3"
bun                     = "1.2.19"
flux2                   = "2.6.4"
hadolint                = "2.12.0"
kind                    = "0.29.0"
kubectl                 = "1.33.3"
markdownlint-cli2       = "0.18.1"
node                    = "22.17.1"
pre-commit              = "4.2.0"
shellcheck              = "0.10.0"
slsa-verifier           = "2.7.0"
terraform               = "1.6.6"
tflint                  = "0.58.1"
uv                      = "0.8.3"
yamllint                = "1.37.1"
"aqua:kyverno/chainsaw" = "0.2.12"
"npm:renovate"          = "41.45.0"

[settings]
disable_backends = ["asdf", "dotnet", "gem", "spm", "vfox"]

[settings.npm]
bun = true

[settings.pipx]
uvx = true
