---
# yamllint disable rule:line-length
name: shellcheck

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      files:
        required: false
        type: string
        default: 'ALL'
      mise_ignore_cfg:
        required: false
        type: string
        default: ""
      mise_log_level:
        required: false
        type: string
        default: "info"

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup repository and tools
      uses: ppat/github-workflows/actions/setup-repository-tools@main # x-release-please-version
      with:
        git_ref: ${{ inputs.git_ref }}
        mise_ignore_cfg: ${{ inputs.mise_ignore_cfg }}
        mise_log_level: ${{ inputs.mise_log_level }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint shell scripts
      env:
        SHELLSCRIPT_FILES: ${{ inputs.files }}
      shell: bash
      working-directory: ./current
      # yamllint disable-line rule:indentation
      run: |
        if [[ "${SHELLSCRIPT_FILES}" == "ALL" ]]; then
          set -x
          find . -type f -not -path './node_modules/*' -not -path './.git/*' -not -path ./bun.lock -executable -exec shellcheck --rcfile .shellcheckrc {} +
          set +x
        else
          set -x
          shellcheck --rcfile .shellcheckrc $SHELLSCRIPT_FILES
          set +x
        fi
