---
# yamllint disable rule:line-length
name: shellcheck

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      files:
        required: false
        type: string
        default: 'ALL'
      mise_ignore_cfg:
        required: false
        type: string
        default: ""
      mise_log_level:
        required: false
        type: string
        default: "warn"

env:
  # renovate: datasource=github-releases depName=koalaman/shellcheck
  SHELLCHECK_VERSION: "v0.11.0"

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup repository and tools
      uses: ppat/homelab-ops-actions/actions/setup-repository-tools@35903fc15a8d39b5c6d5eb51350324a227a5a814 # v1.0.1
      with:
        current_git_ref: ${{ inputs.git_ref }}
        current_repository: ${{ github.repository }}
        mise_ignore_cfg: ${{ inputs.mise_ignore_cfg }}
        mise_log_level: ${{ inputs.mise_log_level }}
        # renovate: datasource=github-releases depName=jdx/mise
        mise_version: "v2025.10.10"
        token: ${{ secrets.GITHUB_TOKEN }}
        mise_toml: |
          [tools]
          shellcheck = "${{ env.SHELLCHECK_VERSION }}"

    - name: Lint shell scripts
      env:
        SHELLSCRIPT_FILES: ${{ inputs.files }}
      shell: bash
      working-directory: ./current
      # yamllint disable-line rule:indentation
      run: |
        if [[ "${SHELLSCRIPT_FILES}" == "ALL" ]]; then
          set -x
          find . -type f -not -path './node_modules/*' -not -path './.git/*' -not -path ./bun.lock -executable -exec shellcheck --rcfile .shellcheckrc {} +
          set +x
        else
          set -x
          shellcheck --rcfile .shellcheckrc $SHELLSCRIPT_FILES
          set +x
        fi
