---
# yamllint disable rule:line-length
name: markdown

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      files:
        required: false
        type: string
        default: 'ALL'
      mise_ignore_cfg:
        required: false
        type: string
        default: ""
      mise_log_level:
        required: false
        type: string
        default: "info"

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup repository and tools
      uses: ppat/github-workflows/actions/setup-repository-tools@refactor-setup-tools
      with:
        git_ref: ${{ inputs.git_ref }}
        mise_ignore_cfg: ${{ inputs.mise_ignore_cfg }}
        mise_log_level: ${{ inputs.mise_log_level }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Lint markdown files
      env:
        MARKDOWN_FILES: ${{ inputs.files }}
      shell: bash
      working-directory: ./current
      # yamllint disable-line rule:indentation
      run: |
        CONFIG_PARAM=""
        if [[ -f ./.markdownlint-cli2.yaml ]]; then
          CONFIG_PARAM="--config ./.markdownlint-cli2.yaml"
        elif [[ -f ./.markdownlint.yaml ]]; then
          CONFIG_PARAM="--config ./.markdownlint.yaml"
        fi
        if [[ "${MARKDOWN_FILES}" == "ALL" ]]; then
          markdownlint-cli2 "**/*.md" $CONFIG_PARAM
        else
          FILTERED=""
          for file in ${MARKDOWN_FILES}; do
            if [[ "${file}" != *"CHANGELOG.md"* ]]; then
              FILTERED="${FILTERED} ${file}"
            fi
          done

          if [[ -z "${FILTERED}" ]]; then
            echo "No files to lint after filtering."
            exit 0
          fi
          set -x
          markdownlint-cli2 ${FILTERED} $CONFIG_PARAM
          set +x
        fi
