---
# yamllint disable rule:line-length
name: zizmor

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      mise_ignore_cfg:
        required: false
        type: string
        default: ""
      mise_log_level:
        required: false
        type: string
        default: "warn"

env:
  # renovate: datasource=github-releases depName=zizmorcore/zizmor
  ZIZMOR_VERSION: "v1.27.0"

jobs:
  zizmor:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup repository and tools
      uses: ppat/homelab-ops-actions/actions/setup-repository-tools@f1ae73db4ab080b7e8dc66d078e5905d5ca526cb # v2.1.0
      with:
        current_git_ref: ${{ inputs.git_ref }}
        current_repository: ${{ github.repository }}
        mise_ignore_cfg: ${{ inputs.mise_ignore_cfg }}
        mise_log_level: ${{ inputs.mise_log_level }}
        token: ${{ secrets.GITHUB_TOKEN }}
        mise_toml: |
          [tools]
          "aqua:zizmorcore/zizmor" = "${{ env.ZIZMOR_VERSION }}"

    - name: Audit github actions with zizmor
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      working-directory: ./current
      run: |
        zizmor --format=github --min-severity=medium --min-confidence=high --persona=regular .
