---
# yamllint disable rule:line-length
name: markdown

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      files:
        required: false
        type: string
        default: 'ALL'
      mise_ignore_cfg:
        required: false
        type: string
        default: ""
      mise_log_level:
        required: false
        type: string
        default: "warn"

env:
  # renovate: datasource=npm depName=bun
  BUN_VERSION: "1.3.1"
  # renovate: datasource=github-releases depName=DavidAnson/markdownlint-cli2
  MARKDOWNLINT_CLIV2_VERSION: "v0.18.1"
  # renovate: datasource=node-version
  NODE_VERSION: "22.20.0"

jobs:
  markdownlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
    - name: Setup repository and tools
      uses: ppat/homelab-ops-actions/actions/setup-repository-tools@35903fc15a8d39b5c6d5eb51350324a227a5a814 # v1.0.1
      with:
        current_git_ref: ${{ inputs.git_ref }}
        current_repository: ${{ github.repository }}
        mise_ignore_cfg: ${{ inputs.mise_ignore_cfg }}
        mise_log_level: ${{ inputs.mise_log_level }}
        # renovate: datasource=github-releases depName=jdx/mise
        mise_version: "v2025.10.18"
        token: ${{ secrets.GITHUB_TOKEN }}
        mise_toml: |
          [tools]
          bun               = "${{ env.BUN_VERSION }}"
          markdownlint-cli2 = "${{ env.MARKDOWNLINT_CLIV2_VERSION }}"
          node              = "${{ env.NODE_VERSION }}"
          [settings.npm]
          bun               = true

    - name: Lint markdown files
      env:
        MARKDOWN_FILES: ${{ inputs.files }}
      shell: bash
      working-directory: ./current
      # yamllint disable-line rule:indentation
      run: |
        CONFIG_PARAM=""
        if [[ -f ./.markdownlint-cli2.yaml ]]; then
          CONFIG_PARAM="--config ./.markdownlint-cli2.yaml"
        elif [[ -f ./.markdownlint.yaml ]]; then
          CONFIG_PARAM="--config ./.markdownlint.yaml"
        fi
        if [[ "${MARKDOWN_FILES}" == "ALL" ]]; then
          markdownlint-cli2 "**/*.md" $CONFIG_PARAM
        else
          FILTERED=""
          for file in ${MARKDOWN_FILES}; do
            if [[ "${file}" != *"CHANGELOG.md"* ]]; then
              FILTERED="${FILTERED} ${file}"
            fi
          done

          if [[ -z "${FILTERED}" ]]; then
            echo "No files to lint after filtering."
            exit 0
          fi
          set -x
          markdownlint-cli2 ${FILTERED} $CONFIG_PARAM
          set +x
        fi
