---
# yamllint disable rule:line-length
name: release

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      timeout:
        required: false
        type: number
        default: 10
    secrets:
      renovate_app_id:
        required: true
      renovate_app_private_key:
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout }}
    steps:
    - name: Generate github app token for renovate
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
      id: app-token
      with:
        app-id: ${{ secrets.renovate_app_id }}
        private-key: ${{ secrets.renovate_app_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Release Please
      uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
      id: release
      with:
        repo-url: ${{ inputs.repository }}
        token: ${{ steps.app-token.outputs.token }}
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json

    - name: Show Release Please Output
      env:
        RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
      run: |
        echo ${RELEASE_PLEASE_OUTPUT} | jq .
