---
# yamllint disable rule:line-length
name: release-please

on:
  workflow_call:
    secrets:
      app_id:
        required: true
      app_private_key:
        required: true

jobs:
  release-please:
    if: ${{ (github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - name: Generate github app token
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
      id: app-token
      with:
        app-id: ${{ secrets.app_id }}
        private-key: ${{ secrets.app_private_key }}
        owner: ${{ github.repository_owner }}

    - name: Release Please
      uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4
      id: release
      with:
        repo-url: ${{ github.repository }}
        token: ${{ steps.app-token.outputs.token }}
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json

    - name: Show Release Please Output
      env:
        RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
      run: |
        echo ${RELEASE_PLEASE_OUTPUT} | jq .
