---
# yamllint disable rule:line-length
name: self-lint

on:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changed-files.yaml
    with:
      # yamllint disable-line rule:indentation
      config: |
        files_yaml: |
          actions:
          - .github/workflows/**
          docker:
          - '**/Dockerfile'
          markdown:
          - '**.md'
          renovate:
          - .github/renovate.json
          - .github/renovate/**
          shellscripts:
          - '**.sh'
          yaml:
          - '**.yaml'
      git_ref: ${{ github.head_ref }}

  commit-messages:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/lint-commit-messages.yaml
    with:
      git_ref: ${{ github.head_ref }}
      fetch_depth: ${{ github.event.pull_request.commits || 0 }}
      from: ${{ github.event.pull_request.head.sha || 'HEAD' }}~${{ github.event.pull_request.commits || '1' }}
      to: ${{ github.event.pull_request.head.sha || 'HEAD' }}

  github-actions:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.actions_any_changed == 'true' }}
    uses: ./.github/workflows/lint-github-actions.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.actions_all_changed_files }}

  docker-files:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.docker_any_changed == 'true' }}
    uses: ./.github/workflows/lint-hadolint.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.docker_all_changed_files }}

  markdown:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.markdown_any_changed == 'true' }}
    uses: ./.github/workflows/lint-markdown.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.markdown_all_changed_files }}

  pre-commit:
    uses: ./.github/workflows/lint-pre-commit.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}

  renovate-config-check:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.renovate_any_changed == 'true' }}
    uses: ./.github/workflows/lint-renovate-config-check.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.renovate_all_changed_files }}

  shellcheck:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.shellscripts_any_changed == 'true' }}
    uses: ./.github/workflows/lint-shellcheck.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.shellscripts_all_changed_files }}

  yaml:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || needs.detect-changes.outputs.yaml_any_changed == 'true' }}
    uses: ./.github/workflows/lint-yaml.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || needs.detect-changes.outputs.yaml_all_changed_files }}
