---
# yamllint disable rule:line-length
name: self-lint

on:
  pull_request:
  schedule:
  - cron: '0 4 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changed-files.yaml
    with:
      # yamllint disable-line rule:indentation
      files_yaml: |
        actions:
        - .github/workflows/**
        markdown:
        - '**.md'
        renovate:
        - .github/renovate.json
        - .github/renovate/**
        yaml:
        - '**.yaml'
        - '**.yml'
      git_ref: ${{ github.head_ref || github.ref }}

  commit-messages:
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/lint-commit-messages.yaml
    with:
      git_ref: ${{ github.head_ref }}
      fetch_depth: ${{ github.event.pull_request.commits || 0 }}
      from: ${{ github.event.pull_request.head.sha || 'HEAD' }}~${{ github.event.pull_request.commits || '1' }}
      to: ${{ github.event.pull_request.head.sha || 'HEAD' }}

  github-actions:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || fromJSON(needs.detect-changes.outputs.results).actions_any_changed == 'true' }}
    uses: ./.github/workflows/lint-github-actions.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || fromJSON(needs.detect-changes.outputs.results).actions_all_changed_files }}

  markdown:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || fromJSON(needs.detect-changes.outputs.results).markdown_any_changed == 'true' }}
    uses: ./.github/workflows/lint-markdown.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || fromJSON(needs.detect-changes.outputs.results).markdown_all_changed_files }}

  pre-commit:
    uses: ./.github/workflows/lint-pre-commit.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}

  renovate-config-check:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || fromJSON(needs.detect-changes.outputs.results).renovate_any_changed == 'true' }}
    uses: ./.github/workflows/lint-renovate-config-check.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || fromJSON(needs.detect-changes.outputs.results).renovate_all_changed_files }}

  yaml:
    needs: [detect-changes]
    if: ${{ github.event_name != 'pull_request' || fromJSON(needs.detect-changes.outputs.results).yaml_any_changed == 'true' }}
    uses: ./.github/workflows/lint-yaml.yaml
    with:
      git_ref: ${{ github.head_ref || github.ref }}
      files: ${{ github.event_name != 'pull_request' && 'ALL' || fromJSON(needs.detect-changes.outputs.results).yaml_all_changed_files }}
