---
# yamllint disable rule:line-length
name: self-renovate

on:
  pull_request:
    paths:
    - '.github/workflows/renovate.yaml'
    - '.github/workflows/self-renovate.yaml'
  schedule:
  - cron: '0 8 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    uses: ./.github/workflows/renovate.yaml
    with:
      dry_run: ${{ github.event_name == 'pull_request' }}
      git_ref: ${{ github.head_ref || github.ref }}
      log_level: debug
    secrets:
      app_id: ${{ secrets.RENOVATE_APP_ID }}
      app_private_key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
